# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
# 클러스터에 의해 동적으로 프로비저닝되는 Mysql Storage에 대한 'Persistent Voulume Claim'(PVC) 정의
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: studyon-db-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: studyon-db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi #This will tell kubernetes about the amount of space we are trying to claim.
