kind: Service
apiVersion: v1
metadata:
  name: spring-oauth-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: server-port
  selector:
    app: spring-oauth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-oauth-deployment
spec:
  selector:
    matchLabels:
      app: spring-oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-oauth
    spec:
      containers:
        - name: spring-oauth
          image: kyungju620/real-oauth-service:v6
          ports:
            - containerPort: 8080
