apiVersion: v1
kind: Service
metadata:
  name: realtime-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: realtime-backend
  type: NodePort
  ports:
    - port: 9000
      targetPort: 8000
      protocol: TCP
